site_name: "ESP32 Distance"
site_description: "This project is a proof of concept project to learn about GH Codespaces and GH Copilot including a Hands-on Workshop"

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.footer
    - content.full_width

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.highlight

extra_javascript:
  - https://unpkg.com/mermaid@10.9.1/dist/mermaid.min.js
  - javascripts/mermaid-init.js

nav:
  - Home: index.md
  - Documentation:
    - Architecture: 
      - Overview: architecture/README.md
    - Development:
      - Overview: development/README.md
      - Dev Container: development/devcontainer.md
      - QEMU Emulator: development/qemu-emulator.md
      - Debugging: development/debugging.md
      - Network Internals: development/qemu-network-internals.md
      - Pre-commit Hooks: development/pre-commit-hooks.md
    - Known Limitations: known-limitations.md
    - Requirements: 
      - Overview: requirements/README.md
      - System: requirements/system-requirements.md
      - Distance sensor: requirements/distance-sensor-requirements.md
      - LED controller: requirements/led-controller-requirements.md
      - Display: requirements/display-requirements.md
      - Configuration: requirements/config-requirements.md
      - Startup test: requirements/startup-test-requirements.md
      - Web server: requirements/web-server-requirements.md
    - Design:
      - System: design/system-design.md
      - Distance sensor: design/distance-sensor-design.md
      - LED controller: design/led-controller-design.md
      - Display: design/display-design.md
      - Configuration: design/config-design.md
      - Startup test: design/startup-test-design.md
    - Tests:
      - Emulator: emulator-support.md
      - Config tests: test/config-tests.md
    - Planning:
      - Features: planning/Features-intended.md
  - Workshop:
    - Overview: workshop/README.md
    - Prerequisites: workshop/prerequisites.md
    - Getting Started Hardware: workshop/hardwaresetup.md
    - Getting Started Software: workshop/gettingstartet.md
    - Exercises: workshop/exercises.md
  - API: api/README.md
  - Legal:
    - Impressum: legal/impressum.md
    - Datenschutz: legal/datenschutz.md

plugins:
  - search
  - mkdocstrings


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/enthali/esp32-distance
  generator: false

copyright: |
  &copy; 2025 Georg Doll - 
  <a href="/legal/impressum/">Impressum</a> | 
  <a href="/legal/datenschutz/">Datenschutz</a>